version: '3.7'

services:
  splunk:
    hostname: splunkenterprise
    image: splunk/splunk:latest
    environment:
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_START_ARGS=--accept-license --no-prompt --answer-yes
      - SPLUNK_USERNAME=admin
      - SPLUNK_PASSWORD=password
    restart: always
    volumes:
      - opt_splunk_etc:/opt/splunk/etc
      - opt_splunk_var:/opt/splunk/var
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
      - "514:514/udp"
    restart: always
    networks:
      - splunk-ldap
      
  ldap:
    container_name: ldap
    image: osixia/openldap
    ports:
      - "389:389"
      - "636:636"
    command: [--copy-service,  --loglevel, debug]
    volumes:
      - ldap_config:/etc/ldap/slapd.d
      - ldap_database:/var/lib/ldap
    environment:
      - LDAP_ADMIN_PASSWORD=password
      - LDAP_BASE_DN=dc=mydomain,dc=com
      - LDAP_DOMAIN=mydomain.com
    networks:
      - splunk-ldap
  phpldapadmin:
    container_name: phpldapadmin
    image: osixia/phpldapadmin
    ports:
      - "80:80"
    environment:
      - PHPLDAPADMIN_HTTPS="false"
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
    links:
      - ldap
    depends_on:
      - ldap
    networks:
      - splunk-ldap
    #
networks:
  splunk-ldap:
    # use the bridge driver, but enable IPv6
    driver: bridge
    
volumes:
  ldap_config:
  ldap_database:
  opt_splunk_etc:
  opt_splunk_var:
  

